services:
  - type: web
    name: portfolio-laravel
    env: php
    branch: main
    plan: free
    buildCommand: |
      composer install
      npm install
      npm run build
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
